### ISSUE TITLE
Package Types Validation Missing Options

### ISSUE THREAD

**Issue by jlrgraham23** [jfrog/terraform-provider-artifactory#71]
The list of valid repository types seems to be missing a few options listed on the JFrog API docs:
[https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON](https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON)

**Source Terraform**

```
resource "artifactory_local_repository" "conan-local" {
  key          = "conan-local"
  package_type = "conan"
}
```

**Failure Output**

```
Error: expected package_type to be one of [alpine bower chef cocoapods composer cran debian docker gems generic go gradle helm ivy maven npm conda nuget opkg p2 puppet pypi rpm sbt vcs yum], got conan
--
8 |  
9 | on terraform/repo_conan.tf line 1, in resource "artifactory_local_repository" "conan-local":
10 | 1: resource "artifactory_local_repository" "conan-local" {
```

Artifactory version: 7.10.5
Terraform version: 0.14.9
Artifactory provider version: 2.2.9

**Expected behavior**

Create and manage the repository resources, working before the type validation was added.

**Comment by chb0github** [comment]
mmmmmmmmmmm - that should have been fixed with this release..... 🤦

**Comment by jlrgraham23** [comment]
Hi @chb0github many thanks for getting this processed and merged so quickly!

Just double checking, is there another step to get this into the Terraform Registry or do we expect that to get published sometime soon?  I'm still seeing 2.2.9 as current there.

Thanks again!

**Comment by chb0github** [comment]
Hmmmmmm, it should have already been published. I will double check

**Comment by chb0github** [comment]
Ok, GH actions are choking without explanation. This will take some more digging. I will work on this. I have reopened the ticket

**Comment by chb0github** [comment]
This is fixed. Let me know if you continue to have issues
